### PR TITLE
3D models for the IKEA frame

### PR DESCRIPTION
**Pull request by jschrempp**
Two files that can be 3D printed. One to hold the eInk display in correct position behind the acrylic front in the IKEA frame, and a second to go behind the IKEA frame cardboard back with mounting posts for the RPi.

Two corresponding STEP files exported from Fusion 360 so that others can modify the parts if they so desire.

### CODE REVIEW

**Review by qubist — CHANGES_REQUESTED** [review]
These look great! I'd love to see a picture of it all assembled to get a better sense of how it works.

In terms of the PR, it makes the most sense to add a link to these files in the Readme instead of committing them to the repo itself:
* This repo gets cloned to Raspberry Pis when updating or installing the software, and it doesn't make sense for these files to be on the RPi running the VSMP
* If they're hosted elsewhere (Thingiverse, Prusaprinters, Thangs), 3D–printing-specific discussions about them (and VSMP hardware assembly) can be had there instead of here, where not everyone is interested in 3D printing or using the IKEA frame.

That said, a small Hardware section with a collection of links may be in order, with this, [my Instructable](https://www.instructables.com/Very-Slow-Movie-Player/), @TomWhitwell's original instructions of course, and other assembly guides or resources for the hardware-side of the VSMP.

@jschrempp does that make sense to you? Are you interested in taking a stab at that hardware section in the Readme?

**Comment by missionfloyd** [comment]
A hardware section in the wiki would be good for this kind of stuff.

**Comment by robweber** [comment]
I think the Wiki would be a great place for these too. The wiki is actually just a git repo tied to the wiki tab of the project. We can add files and such to it. This could start a whole page of links or downloads to compatible frame solutions.

**Comment by jschrempp** [comment]
I would be happy to put this in the wiki, but don't have permission to edit the wiki.

You could add my Instructable to the wiki:  https://www.instructables.com/Slow-Movie-Player/

Jim

**Comment by robweber** [comment]
Took a first pass at adding this to the wiki: https://github.com/TomWhitwell/SlowMovie/wiki/Guides-and-Frame-Links

**Comment by jschrempp** [comment]
The wiki looks good to me. BTW, I found that my Instructable linked to my GitHub fork. I have changed those links to point to TomWhitwell.

To me you could close out this pull request.

**Pull request closed without merging**
