### PR TITLE
Various Fixes

### PR DESCRIPTION
**Pull request by missionfloyd**
- Extract frames to RAM instead of SD card.
- Get screen dimensions from driver. Now only one line has to be changed to in order use with other screen sizes.
- Correctly scale anamorphic videos.
- Get video framerate from ffmpeg, instead of assuming 24Hz.
- Added contrast adjustment option.
- Added MKV support (actually, any filetype supported by ffmpeg should work)
- The `--file` argument now accepts files in any location.
- Added SIGTERM handler. Gracefully exits now,
- Better handling of log files; only create log for current video.
- Create log and video directories if missing, rather than crashing.
- Added option to automatically adjust delay to compensate for time taken to display a frame.
- Added systemd service.
  To install, copy `slowmovie.service` to `/etc/systemd/system`, then run `sudo systemctl daemon-reload`
  Start/stop/restart: `sudo systemctl [start|stop|restart] slowmovie`
  Enable/disable autorun: `sudo systemctl [enable|disable] slowmovie`
- Added config file support (optional, requires configargparse)
- Added random file option
- Added video directory option

### CODE REVIEW

**Comment by TomWhitwell** [comment]
Hi, this looks great - thank you! You can contact me at tom@musicthing.co.uk if you want to discuss 
Tom

**Comment by missionfloyd** [comment]
I figured I might've changed too much all at once. I guess I'll reopen it.

**Comment by missionfloyd** [comment]
Oh well

**Comment by TomWhitwell** [comment]
Just testing this now - I was running Python 2, so getting a few odd errors, also currently experimenting with a Pi zero which has different issues, will test with pi 4 when I get it set up again

**Comment by missionfloyd** [comment]
Is the pi zero rebooting when you try to run it? If so, use the wires instead.

And I think the only thing I have in it that's incompatible with python2 is a few f-strings. Changing them to old style string formatting should make it work with python2, but I haven't tried that.

**Comment by cheprasov** [comment]
Hi @TomWhitwell Thanks a lot for the project :) Just created today the slow movie frame on Raspberry Pi Zero.
Hi @missionfloyd Thanks for your work :) Looks like it would be interesting improvements and happy to see that the project is supported by people :)

**Comment by missionfloyd** [comment]
Since #29 is based largely on this, and It's stable, I'm gonna go ahead and merge it. Then further improvements from the other PRs can be incorporated. This will likely create merge conflicts which will have to be resolved, but this seems to make more sense than manually combining PRs.

**Comment by qubist** [comment]
Since many of the improvements from this were already manually combined into #29, once that's merged it'll probably just override any changes to master before then... The point was to manually merge in order to get the best pieces of many conflicting/redundant improvements

**Comment by missionfloyd** [comment]
It just seems like you've made it harder than it needed to be. Could've just forked mine, since that's where the majority of the changes are coming from.

**Comment by robweber** [comment]
The two major missing pieces are the service and configargparse additions. I could see revisiting those in another PR (The Big Merge is getting big as it is) but we'll want those eventually. 

FYI - I'm going to make a tag of the current state of "master" before we go mucking about too much further in there. I'll just call it v0.1 per Tom's v0.2 designation for his other work. At least we'll know exactly at what point we screwed it all up :)

**Comment by missionfloyd** [comment]
This is what branches are for. My stuff was done and ready to merge, so I've put it in https://github.com/TomWhitwell/SlowMovie/tree/slowmovie-next for now. It shouldn't be too much trouble to add in the other changes. Then it can be merged to master when ready.

**Comment by robweber** [comment]
Sounds good. I think in this case we had a lot of PRs and modifications across a lot of places going back months. I know the one I originally made overlapped with some of your changes too and qubist's branch was a further mix of those. Once that large PR is merged in we can see how the rest shakes out. Going forward a more traditional branch -> PR process can be used to increment changes more cohesively. Growing pains I guess.

**Comment by qubist** [comment]
Thanks @missionfloyd, I appreciate all your work and thought on this code, and I agree that a lot of the improvements are coming from your fork. If I had seen the full scope of the project before starting my own improvements I think I would've done things differently, and I hear you pointing that out.

As it stands, I've completed most of the "harder than it needed to be" work, so I think moving forward makes sense. If there's things that this whole PR made things harder on your side, I'd love to know about them and help if I can.

**Comment by qubist** [comment]
> Going forward a more traditional branch -> PR process can be used to increment changes more cohesively.

Creating a steady base for this to happen is my goal :)

**Comment by missionfloyd** [comment]
I had a steady base, many of the things you've been working on already worked. I even made a branch so we could all work on it, but as it is now we have to filter everything through you.

**Comment by qubist** [comment]
I totally see that. I'm really sorry about not merging your PR in and working from there. I'm somewhat new to this and didn't know the whole situation at the time. I really want to find a way to add all our contributions in a way that's best for the project. I'd love to jump on a call with you both sometime soon to talk synchronously about all the complications of the situation and how best to move forward.

**Pull request merged**
